apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- includeCRDs: true
  name: proxmox-csi-plugin
  namespace: csi-proxmox
  releaseName: proxmox-csi-plugin
  repo: oci://ghcr.io/sergelogvinov/charts
  valuesFile: values.yaml
  version: 0.2.9

patches:
- patch: |-
    - op: replace
      path: /volumeBindingMode
      value: Immediate
  target:
    kind: StorageClass
    name: proxmox-csi
