storageClass:
  - name: proxmox-csi
    cache: writethrough
    fstype: ext4
    reclaimPolicy: Retain
    ssd: true
    storage: local-lvm
    mountOptions:
      - noatime
    volumeBindingMode: Immediate
