apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: firefly

resources:
  - ns.yaml

helmCharts:
  - name: firefly-iii-stack
    repo: https://github.com/firefly-iii/firefly-iii/
    releaseName: firefly
    namespace: firefly
    valuesFile: values.yaml
    version: 0.8.0
