apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: proxmox-csi
  csi:
    driver: csi.proxmox.sinextra.dev
    volumeHandle: csi-storage # This should match your Proxmox storage ID
